name: Build Small APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0' # Adjust if needed
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Build Split APKs
        # Building split APKs reduces size by creating separate APKs per CPU architecture.
        # Obfuscation and split-debug-info further reduce size and secure code.
        run: flutter build apk --split-per-abi --obfuscate --split-debug-info=build/app/outputs/flutter-apk/app-obfuscation-info

      - name: Upload arm64-v8a APK
        uses: actions/upload-artifact@v4
        with:
          name: smart-pos-arm64-v8a
          path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk

      - name: Upload armeabi-v7a APK
        uses: actions/upload-artifact@v4
        with:
          name: smart-pos-armeabi-v7a
          path: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
